# Generated by Django 4.0.5 on 2022-06-15 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('gar', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
    ]
