# Generated by Django 4.0.5 on 2022-07-05 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_auto_gar_alter_auto_title_alter_auto_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roadway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Марка, модель')),
                ('factory', models.CharField(max_length=100, verbose_name='Завод-изготовитель')),
                ('image', models.ImageField(upload_to='', verbose_name='Фото')),
            ],
        ),
        migrations.AlterField(
            model_name='auto',
            name='gar',
            field=models.CharField(max_length=5, verbose_name='Гар.№'),
        ),
    ]
