# Generated by Django 4.0.5 on 2022-07-06 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_roadway_alter_auto_gar'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Roadway',
            new_name='KDM',
        ),
    ]
