# Generated by Django 4.0.5 on 2022-07-06 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_rename_roadway_kdm'),
    ]

    operations = [
        migrations.CreateModel(
            name='PUMVS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Марка, модель')),
                ('factory', models.CharField(max_length=100, verbose_name='Завод-изготовитель')),
                ('image', models.ImageField(upload_to='', verbose_name='Фото')),
            ],
        ),
        migrations.CreateModel(
            name='PUPRICEP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Марка, модель')),
                ('factory', models.CharField(max_length=100, verbose_name='Завод-изготовитель')),
                ('image', models.ImageField(upload_to='', verbose_name='Фото')),
            ],
        ),
        migrations.CreateModel(
            name='VPM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Марка, модель')),
                ('factory', models.CharField(max_length=100, verbose_name='Завод-изготовитель')),
                ('image', models.ImageField(upload_to='', verbose_name='Фото')),
            ],
        ),
    ]
