# Generated by Django 4.0.5 on 2022-07-06 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_pumvs_pupricep_vpm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pumvs',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Фото'),
        ),
    ]
