# Generated by Django 4.0.5 on 2022-07-06 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_alter_pumvs_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kdm',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='pumvs',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Фото'),
        ),
    ]
