# Generated by Django 4.0.5 on 2022-07-07 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_alter_kdm_image_alter_pumvs_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='kdm',
            name='chassis',
            field=models.CharField(blank=True, max_length=50, verbose_name='Шасси'),
        ),
        migrations.AlterField(
            model_name='kdm',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Фото'),
        ),
    ]
