# Generated by Django 4.0.5 on 2022-07-18 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_kdmi'),
    ]

    operations = [
        migrations.AddField(
            model_name='kdm',
            name='image1',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='kdm',
            name='image2',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Фото'),
        ),
    ]
