# Generated by Django 4.0.5 on 2022-07-20 18:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_kdm_image1_kdm_image2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kdm',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
