# Generated by Django 4.0.5 on 2022-07-20 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_alter_kdm_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kdm',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
