# Generated by Django 4.0.5 on 2022-07-21 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0014_alter_kdm_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='kdm',
            name='image10',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='kdm',
            name='image3',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='kdm',
            name='image4',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='kdm',
            name='image5',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='kdm',
            name='image6',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='kdm',
            name='image7',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='kdm',
            name='image8',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='kdm',
            name='image9',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Фото'),
        ),
        migrations.DeleteModel(
            name='KDMI',
        ),
    ]
