# Generated by Django 4.0.5 on 2022-07-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0015_kdm_image10_kdm_image3_kdm_image4_kdm_image5_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kdm',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='kdm',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Марка, модель'),
        ),
    ]
