# Generated by Django 4.0.5 on 2022-07-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0016_alter_kdm_image_alter_kdm_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Createphotokdm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, upload_to='', verbose_name='Фото1')),
                ('image2', models.ImageField(blank=True, upload_to='', verbose_name='Фото2')),
                ('image3', models.ImageField(blank=True, upload_to='', verbose_name='Фото3')),
            ],
        ),
        migrations.AlterField(
            model_name='kdm',
            name='image1',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Фото1'),
        ),
        migrations.AlterField(
            model_name='kdm',
            name='image10',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Фото10'),
        ),
        migrations.AlterField(
            model_name='kdm',
            name='image2',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Фото2'),
        ),
        migrations.AlterField(
            model_name='kdm',
            name='image3',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Фото3'),
        ),
        migrations.AlterField(
            model_name='kdm',
            name='image4',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Фото4'),
        ),
        migrations.AlterField(
            model_name='kdm',
            name='image5',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Фото5'),
        ),
        migrations.AlterField(
            model_name='kdm',
            name='image6',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Фото6'),
        ),
        migrations.AlterField(
            model_name='kdm',
            name='image7',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Фото7'),
        ),
        migrations.AlterField(
            model_name='kdm',
            name='image8',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Фото8'),
        ),
        migrations.AlterField(
            model_name='kdm',
            name='image9',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Фото9'),
        ),
    ]
