# Generated by Django 4.0.5 on 2022-07-22 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0018_createphotokdm_im'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createphotokdm',
            name='im',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.kdm'),
        ),
    ]
