# Generated by Django 4.0.5 on 2022-07-22 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0020_alter_createphotokdm_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createphotokdm',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
