# Generated by Django 4.0.5 on 2022-07-23 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0021_alter_createphotokdm_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createphotokdm',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото1'),
        ),
        migrations.AlterField(
            model_name='createphotokdm',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото2'),
        ),
        migrations.AlterField(
            model_name='createphotokdm',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото3'),
        ),
    ]
