# Generated by Django 4.0.5 on 2022-07-25 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0022_alter_createphotokdm_image1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kdm',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарии'),
        ),
        migrations.AlterField(
            model_name='kdm',
            name='tech',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Технические характеристики'),
        ),
    ]
