# Generated by Django 4.0.5 on 2022-07-28 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0023_alter_kdm_comment_alter_kdm_tech'),
    ]

    operations = [
        migrations.CreateModel(
            name='Createcommentskdm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарии')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.kdm')),
            ],
        ),
    ]
