# Generated by Django 4.0.5 on 2022-07-30 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0024_createcommentskdm'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechKDM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech', models.FileField(blank=True, null=True, upload_to='', verbose_name='Технические характеристики')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.kdm')),
            ],
        ),
    ]
