# Generated by Django 4.0.5 on 2022-08-02 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0026_pumvs_chassis_pumvs_comment_pumvs_image1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Createcommentsvpm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
            ],
        ),
        migrations.CreateModel(
            name='Createphotovpm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото1')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото2')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото3')),
            ],
        ),
        migrations.CreateModel(
            name='TechVPM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech', models.FileField(blank=True, null=True, upload_to='', verbose_name='Технические характеристики')),
            ],
        ),
        migrations.DeleteModel(
            name='PUPRICEP',
        ),
        migrations.AddField(
            model_name='vpm',
            name='chassis',
            field=models.CharField(blank=True, max_length=50, verbose_name='Шасси'),
        ),
        migrations.AddField(
            model_name='vpm',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарии'),
        ),
        migrations.AddField(
            model_name='vpm',
            name='image1',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Фото1'),
        ),
        migrations.AddField(
            model_name='vpm',
            name='image10',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Фото10'),
        ),
        migrations.AddField(
            model_name='vpm',
            name='image2',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Фото2'),
        ),
        migrations.AddField(
            model_name='vpm',
            name='image3',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Фото3'),
        ),
        migrations.AddField(
            model_name='vpm',
            name='image4',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Фото4'),
        ),
        migrations.AddField(
            model_name='vpm',
            name='image5',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Фото5'),
        ),
        migrations.AddField(
            model_name='vpm',
            name='image6',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Фото6'),
        ),
        migrations.AddField(
            model_name='vpm',
            name='image7',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Фото7'),
        ),
        migrations.AddField(
            model_name='vpm',
            name='image8',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Фото8'),
        ),
        migrations.AddField(
            model_name='vpm',
            name='image9',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Фото9'),
        ),
        migrations.AddField(
            model_name='vpm',
            name='tech',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Технические характеристики'),
        ),
        migrations.AlterField(
            model_name='vpm',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vpm',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Марка, модель'),
        ),
        migrations.AddField(
            model_name='techvpm',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.vpm'),
        ),
        migrations.AddField(
            model_name='createphotovpm',
            name='im',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.vpm'),
        ),
        migrations.AddField(
            model_name='createcommentsvpm',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.vpm'),
        ),
    ]
