# Generated by Django 4.0.5 on 2022-08-05 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0030_fp_techfp_createphotofp_createcommentsfp'),
    ]

    operations = [
        migrations.CreateModel(
            name='BULLDOZER',
            fields=[
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Марка, модель')),
                ('factory', models.CharField(max_length=100, verbose_name='Завод-изготовитель')),
                ('image', models.ImageField(upload_to='', verbose_name='Фото')),
                ('image1', models.ImageField(blank=True, upload_to='', verbose_name='Фото1')),
                ('image2', models.ImageField(blank=True, upload_to='', verbose_name='Фото2')),
                ('image3', models.ImageField(blank=True, upload_to='', verbose_name='Фото3')),
                ('image4', models.ImageField(blank=True, upload_to='', verbose_name='Фото4')),
                ('image5', models.ImageField(blank=True, upload_to='', verbose_name='Фото5')),
                ('image6', models.ImageField(blank=True, upload_to='', verbose_name='Фото6')),
                ('image7', models.ImageField(blank=True, upload_to='', verbose_name='Фото7')),
                ('image8', models.ImageField(blank=True, upload_to='', verbose_name='Фото8')),
                ('image9', models.ImageField(blank=True, upload_to='', verbose_name='Фото9')),
                ('image10', models.ImageField(blank=True, upload_to='', verbose_name='Фото10')),
                ('tech', models.FileField(blank=True, null=True, upload_to='', verbose_name='Технические характеристики')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарии')),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='GRADER',
            fields=[
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Марка, модель')),
                ('factory', models.CharField(max_length=100, verbose_name='Завод-изготовитель')),
                ('image', models.ImageField(upload_to='', verbose_name='Фото')),
                ('image1', models.ImageField(blank=True, upload_to='', verbose_name='Фото1')),
                ('image2', models.ImageField(blank=True, upload_to='', verbose_name='Фото2')),
                ('image3', models.ImageField(blank=True, upload_to='', verbose_name='Фото3')),
                ('image4', models.ImageField(blank=True, upload_to='', verbose_name='Фото4')),
                ('image5', models.ImageField(blank=True, upload_to='', verbose_name='Фото5')),
                ('image6', models.ImageField(blank=True, upload_to='', verbose_name='Фото6')),
                ('image7', models.ImageField(blank=True, upload_to='', verbose_name='Фото7')),
                ('image8', models.ImageField(blank=True, upload_to='', verbose_name='Фото8')),
                ('image9', models.ImageField(blank=True, upload_to='', verbose_name='Фото9')),
                ('image10', models.ImageField(blank=True, upload_to='', verbose_name='Фото10')),
                ('tech', models.FileField(blank=True, null=True, upload_to='', verbose_name='Технические характеристики')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарии')),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='SNOWLOADER',
            fields=[
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Марка, модель')),
                ('factory', models.CharField(max_length=100, verbose_name='Завод-изготовитель')),
                ('image', models.ImageField(upload_to='', verbose_name='Фото')),
                ('image1', models.ImageField(blank=True, upload_to='', verbose_name='Фото1')),
                ('image2', models.ImageField(blank=True, upload_to='', verbose_name='Фото2')),
                ('image3', models.ImageField(blank=True, upload_to='', verbose_name='Фото3')),
                ('image4', models.ImageField(blank=True, upload_to='', verbose_name='Фото4')),
                ('image5', models.ImageField(blank=True, upload_to='', verbose_name='Фото5')),
                ('image6', models.ImageField(blank=True, upload_to='', verbose_name='Фото6')),
                ('image7', models.ImageField(blank=True, upload_to='', verbose_name='Фото7')),
                ('image8', models.ImageField(blank=True, upload_to='', verbose_name='Фото8')),
                ('image9', models.ImageField(blank=True, upload_to='', verbose_name='Фото9')),
                ('image10', models.ImageField(blank=True, upload_to='', verbose_name='Фото10')),
                ('tech', models.FileField(blank=True, null=True, upload_to='', verbose_name='Технические характеристики')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарии')),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='SNOWMELTING',
            fields=[
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Марка, модель')),
                ('factory', models.CharField(max_length=100, verbose_name='Завод-изготовитель')),
                ('image', models.ImageField(upload_to='', verbose_name='Фото')),
                ('image1', models.ImageField(blank=True, upload_to='', verbose_name='Фото1')),
                ('image2', models.ImageField(blank=True, upload_to='', verbose_name='Фото2')),
                ('image3', models.ImageField(blank=True, upload_to='', verbose_name='Фото3')),
                ('image4', models.ImageField(blank=True, upload_to='', verbose_name='Фото4')),
                ('image5', models.ImageField(blank=True, upload_to='', verbose_name='Фото5')),
                ('image6', models.ImageField(blank=True, upload_to='', verbose_name='Фото6')),
                ('image7', models.ImageField(blank=True, upload_to='', verbose_name='Фото7')),
                ('image8', models.ImageField(blank=True, upload_to='', verbose_name='Фото8')),
                ('image9', models.ImageField(blank=True, upload_to='', verbose_name='Фото9')),
                ('image10', models.ImageField(blank=True, upload_to='', verbose_name='Фото10')),
                ('tech', models.FileField(blank=True, null=True, upload_to='', verbose_name='Технические характеристики')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарии')),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TechSM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech', models.FileField(blank=True, null=True, upload_to='', verbose_name='Технические характеристики')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.snowmelting')),
            ],
        ),
        migrations.CreateModel(
            name='TechSL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech', models.FileField(blank=True, null=True, upload_to='', verbose_name='Технические характеристики')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.snowloader')),
            ],
        ),
        migrations.CreateModel(
            name='TechGR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech', models.FileField(blank=True, null=True, upload_to='', verbose_name='Технические характеристики')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.grader')),
            ],
        ),
        migrations.CreateModel(
            name='TechBU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech', models.FileField(blank=True, null=True, upload_to='', verbose_name='Технические характеристики')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.bulldozer')),
            ],
        ),
        migrations.CreateModel(
            name='CreatephotoSM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото1')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото2')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото3')),
                ('im', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.snowmelting')),
            ],
        ),
        migrations.CreateModel(
            name='CreatephotoSL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото1')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото2')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото3')),
                ('im', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.snowloader')),
            ],
        ),
        migrations.CreateModel(
            name='CreatephotoGR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото1')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото2')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото3')),
                ('im', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.grader')),
            ],
        ),
        migrations.CreateModel(
            name='CreatephotoBU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото1')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото2')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото3')),
                ('im', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.bulldozer')),
            ],
        ),
        migrations.CreateModel(
            name='CreatecommentsSM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.snowmelting')),
            ],
        ),
        migrations.CreateModel(
            name='CreatecommentsSL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.snowloader')),
            ],
        ),
        migrations.CreateModel(
            name='CreatecommentsGR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.grader')),
            ],
        ),
        migrations.CreateModel(
            name='CreatecommentsBU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.bulldozer')),
            ],
        ),
    ]
