# Generated by Django 4.0.5 on 2022-08-11 18:42

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('service', '0031_bulldozer_grader_snowloader_snowmelting_techsm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='U',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='createcommentsbu',
            name='b',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.u'),
        ),
    ]
