# Generated by Django 4.0.5 on 2022-08-11 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0032_u_createcommentsbu_b'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createcommentsbu',
            name='b',
        ),
        migrations.DeleteModel(
            name='U',
        ),
    ]
